In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

mp = pd.read_csv('my_projects.csv', sep = '|')
patns = pd.read_csv('patterns.csv', sep = '|')
yarn = pd.read_csv('yarn.csv', sep = '|')

In [2]:
mp.head()

,ID,color,item_type,method,fiber_contentID,yarn_weight,completed,start_date,completion_date,patternID
0,1,orange,cardigan,knit,1,worsted,False,11-Oct-2020,NaN,2
1,2,purple,cardigan,crochet,2,worsted,True,15-Sep-2020,04-Oct-2020,15
2,3,green,scarf,knit,1,worsted,True,14-Sep-2018,31-Oct-2019,12
3,4,"purple, white",croptop,crochet,2,worsted,True,02-Apr-2021,06-May-2021,23
4,5,"red, white",plushie,crochet,3,worsted,True,03-Nov-2021,07-Nov-2021,19

In [3]:
mp.dtypes

ID                  int64
color              object
item_type          object
method             object
fiber_contentID     int64
yarn_weight        object
completed            bool
start_date         object
completion_date    object
patternID           int64
dtype: object

In [4]:
patns.head()

   ID             pattern   source
0   1    Kotikova Croptop  youtube
1   2         Berlin Soft  ravelry
2   3       Mistake Braid  ravelry
3   4         Intermingle  ravelry
4   5  Cuddle Me Elephant  ravelry

In [5]:
patns.dtypes

ID          int64
pattern    object
source     object
dtype: object

In [6]:
yarn.head()

   ID           fiber_content
0   1             merino wool
1   2  peruvian highland wool
2   3                 acrylic
3   4      70/20,merino/nylon
4   5    80/20,wool/polyester

In [7]:
yarn.dtypes

ID                int64
fiber_content    object
dtype: object

In [8]:
mp.start_date = pd.to_datetime(mp.start_date, format = '%d-%b-%Y', errors = 'coerce')
mp.start_date.head(10)

0   2020-10-11
1   2020-09-15
2   2018-09-14
3   2021-04-02
4   2021-11-03
5          NaT
6   2020-07-18
7   2020-06-07
8          NaT
9   2020-06-16
Name: start_date, dtype: datetime64[ns]

In [9]:
mp.completion_date = pd.to_datetime(mp.completion_date, format = '%d-%b-%Y', errors = 'coerce')
mp.completion_date.head(10)

0          NaT
1   2020-10-04
2   2019-10-31
3   2021-05-06
4   2021-11-07
5          NaT
6          NaT
7   2020-08-10
8   2020-05-30
9   2020-06-27
Name: completion_date, dtype: datetime64[ns]

In [10]:
(mp['completed'] == True).sum()

23

In [11]:
(mp['completed'] == False).sum()

3

In [12]:
mp

,ID,color,item_type,method,fiber_contentID,yarn_weight,completed,start_date,completion_date,patternID
0,1,orange,cardigan,knit,1,worsted,False,2020-10-11,NaT,2
1,2,purple,cardigan,crochet,2,worsted,True,2020-09-15,2020-10-04,15
2,3,green,scarf,knit,1,worsted,True,2018-09-14,2019-10-31,12
3,4,"purple, white",croptop,crochet,2,worsted,True,2021-04-02,2021-05-06,23
4,5,"red, white",plushie,crochet,3,worsted,True,2021-11-03,2021-11-07,19
5,6,"red, white, yellow",jacket,crochet,3,worsted,True,NaT,NaT,24
6,7,green,sweater,knit,2,worsted,False,2020-07-18,NaT,13
7,8,orange,socks,knit,1,fingering,True,2020-06-07,2020-08-10,4
8,9,"red, orange",plushie,crochet,3,worsted,True,NaT,2020-05-30,17
9,10,"gray, purple",plushie,crochet,3,dk,True,2020-06-16,2020-06-27,5
10,11,"pink, brown",plushie,crochet,2,worsted,True,2020-04-14,2020-04-15,22
11,12,purple,hat,knit,2,worsted,True,2020-04-16,2021-10-10,10
12,13,"blue, orange, yellow",shawl,knit,4,fingering,True,2018-06-01,2018-07-12,21
13,14,"red, brown, green, yellow",plushie,crochet,3,worsted,True,2018-02-02,2018-05-30,9
14,15,"blue, purple, red",socks,knit,3,dk,True,2018-02-17,2018-03-10,16
15,16,green,hat,crochet,3,worsted,True,2018-01-30,2018-01-31,25
16,17,"green, blue, brown",sweater,knit,12,fingering,False,2019-03-18,NaT,6
17,18,"green, blue, pink",bag,knit,5,fingering,True,NaT,2019-11-08,20
18,19,"pink, white, blue",sweater,knit,3,worsted,True,NaT,2019-01-16,11
19,20,purple,sweater,knit,1,fingering,True,2021-01-26,2021-03-02,8
20,21,"orange, white, yellow",hat,crochet,3,worsted,True,NaT,NaT,14
21,22,pink,croptop,crochet,5,fingering,True,2021-12-18,2021-12-21,1
22,23,blue,croptop,crochet,5,fingering,True,2021-12-23,2022-01-01,1
23,24,purple,cardigan,knit,1,fingering,True,2021-11-21,2021-12-25,7
24,25,"green, purple, pink, blue, orange",blanket,crochet,3,bulky,True,NaT,NaT,18
25,26,green,socks,knit,2,worsted,True,2020-07-11,2020-12-11,3

In [13]:
(mp['start_date'].isnull()).sum()

6

In [14]:
mp['start_date'].groupby(mp['start_date'].dt.year).agg('count')

start_date
2018.0    5
2019.0    1
2020.0    8
2021.0    6
Name: start_date, dtype: int64

In [15]:
mp['completion_date'].groupby(mp['completion_date'].dt.year).agg('count')

completion_date
2018.0    4
2019.0    3
2020.0    6
2021.0    6
2022.0    1
Name: completion_date, dtype: int64

In [16]:
mp['start_date'].groupby([mp['start_date'].dt.year, mp['start_date'].dt.month]).agg('count')

start_date  start_date
2018.0      1.0           1
            2.0           2
            6.0           1
            9.0           1
2019.0      3.0           1
2020.0      4.0           2
            6.0           2
            7.0           2
            9.0           1
            10.0          1
2021.0      1.0           1
            4.0           1
            11.0          2
            12.0          2
Name: start_date, dtype: int64

In [17]:
mp['fiber_contentID'].groupby(mp['fiber_contentID']).agg('count')

fiber_contentID
1      5
2      6
3     10
4      1
5      3
12     1
Name: fiber_contentID, dtype: int64